### ISSUE TITLE
Add check every x second death proxy

### ISSUE THREAD

**Issue by Deswer60871** [VladislavKori/Smartproxy#1]
is it possible to add a check, for example, every 5 seconds if the proxy is not dead and if it is turned off, then prevent access to the website due to data leakage

**Comment by VladislavKori** [comment]
I think you mean adding the site to the bypassList, if the proxy does not respond within 5 seconds, did I understand you correctly?

**Comment by VladislavKori** [comment]
according to the idea, you can display a warning, I will try to add such functionality in the next version
